name: Check for common misspellings in PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  codespell-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changes
        uses: tj-actions/changed-files@v45
        with:
          files: |
            **.md
            **.html

      - name: Scan for for common misspellings in text files
        if: steps.changes.outputs.any_changed == 'true'
        uses: codespell-project/actions-codespell@v2
        with:
          check_filenames: true
          path: ${{ steps.changes.outputs.all_changed_files }}
          ignore_words_file: .codespellignore # Ref: https://github.com/codespell-project/actions-codespell/tree/bca0a5887de255a8903221c67b6478c7501c5edc?tab=readme-ov-file#parameter-ignore_words_file

      - name: ðŸ“– Help & Documentation
        if: failure()
        run: |
          echo "### âŒ Spell Check Failed?" >> $GITHUB_STEP_SUMMARY
          echo "ðŸ‘‰ [**Read the SOP: How to Fix Spell Check Errors**](https://mariadbcorp.atlassian.net/wiki/spaces/DOCS/pages/3284140040/Pull+Requests#Method-1%3A-The-%22Quick-Fix%22-(Recommended))" >> $GITHUB_STEP_SUMMARY

